API Migration Automation script - patch 2
e-mission/e-mission-phone pull request #1031
Opened 2023-09-13 22:25 UTC by niccolopaganini

1. Converted the .ipynb file to python scripts (12 in total; each serving their own purpose; explained in README.md)
2. Added a shell script which executes the aforementioned python scripts
3. README.md file included which explaining the whole process
4. Screenshots directory included for README
5. Archive folder containing the .ipynb file (with updated code) and YML file for reference (included if in-case for future reference)

2023-09-13 22:28 UTC, niccolopaganini commented
- Closed #1025 and reopened it here as I made multiple changes and wanted a separate PR for this patch. 
- Issue tracked in https://github.com/e-mission/e-mission-docs/issues/963 -> I will be compiling all the errors faced here (which will be done before 9/14/2023 9AM)

2023-09-14 23:07 UTC, niccolopaganini commented
> * Closed [API Migration Automation script #1025](https://github.com/e-mission/e-mission-phone/pull/1025) and reopened it here as I made multiple changes and wanted a separate PR for this patch.
> * Issue tracked in [Script to narrow down on changes (methods) that's considered for API migration e-mission-docs#963](https://github.com/e-mission/e-mission-docs/issues/963) -> I will be compiling all the errors faced here (which will be done before 9/14/2023 9AM)

Mentioned in issue - Also mentioning here for reference: Spotty internet connection (I couldn't connect my work computer to campus wifi); I will try to update the error logs sometime tonight

2023-09-16 19:02 UTC, shankari requested changes
This is a lot better than the previous notebook, but still needs some cleanup.
High level comments below.

2023-09-16 19:02 UTC, shankari commented on bin/API_migration_scripts/screenshots/CSVs.png
If something can be represented as text, it should be, to make it easier to search, copy/paste etc
In this case, this can be replaced by 

```
$ ls -al 
...
```

2023-09-16 19:02 UTC, shankari commented on bin/API_migration_scripts/screenshots/csv order.png
Ditto

2023-09-22 18:47 UTC, niccolopaganini commented
1. Addressed issues regarding fragmentation (changing from 12 scripts to 4 "head" python scripts) which allows the modularity without being fragmented 
2. Paths have been changed top be relative 
3. API changes link previously had to be changed by the user. Now it can be inputted by the user.
4. Pending: README needs to be updated & setup script needs to be created.

2023-09-23 02:35 UTC, niccolopaganini commented
> 4\. README needs to be updated ✅

2023-09-24 04:49 UTC, shankari commented
> Addressed issues regarding fragmentation (changing from 12 scripts to 4 "head" python scripts) which allows the modularity without being fragmented

What is your rationale for even needing 4 scripts? Why not just combine into one script?

2023-10-03 16:37 UTC, niccolopaganini commented
Not sure what happened but when I deleted the repo on GitHub, the local dir was also deleted. I restored it from a recent HEAD and had to work on it afterward. I have now (hopefully) addressed all the comments. With this push, 
1. I have boiled it down to one python script 
2. Parallelized the process so now instead of taking 4 minutes to run, it takes 28 seconds on average to execute everything
3. Two bash files
     - One to execute everything 
     - One to remove the rest once the work is done
4. Updated README

2023-10-05 04:58 UTC, shankari requested changes

2023-10-05 04:58 UTC, shankari commented on README.md
why is this file included here?

2023-10-05 04:58 UTC, shankari commented on bin/API_migration_scripts/API_changes_identifier.py
> +        if a.has_attr("href") and a["href"].startswith("/sdk/api_diff/33/changes/"):
this is still hardcoded

2023-10-05 04:58 UTC, shankari commented on bin/API_migration_scripts/API_mcf.sh
> +fi
why do we have to write csv files any more given that all the functions are in the same file? We can just pass the dataframes around and avoid the I/O overhead.

2023-10-05 04:58 UTC, shankari commented on bin/API_migration_scripts/API_changes_identifier.py
> +import csv
I had this an earlier comment. Why do we need `csv` instead just using `pandas`?
https://github.com/e-mission/e-mission-phone/pull/1031#discussion_r1327899392

2023-10-05 04:58 UTC, shankari commented on bin/API_migration_scripts/API_changes_identifier.py
> +import csv
Also, where is the `environment.yml` with the new packages needed by this code?

2023-10-05 04:58 UTC, shankari commented on bin/API_migration_scripts/API_changes_identifier.py
> +                unique_packages.add(row[0].strip())  # Remove leading/trailing whitespace
```suggestion
    output_df = match_csv_java(....)
    unique_packages = get_unique_packages(output_df)
```

2023-10-05 04:58 UTC, shankari commented on bin/API_migration_scripts/API_changes_identifier.py
> +            csvwriter.writerow([package])
```suggestion
return packages
```

2023-10-05 04:58 UTC, shankari commented on bin/API_migration_scripts/API_changes_identifier.py
> +
Good job on experimenting with python concurrency.

Although from a design perspective, this is a bit of overkill for what should be a super simple script.
Four minutes is not that long for a script that is run once every year, and concurrency can add complexity that makes it harder to maintain simple scripts.

However, this appears to be embarrassingly parallel, so the complexity seems manageable for now.
So I will not request a change for now, but will just note that simplicity is also a virtue, especially for simple scripts that are not part of the production system.

2023-11-06 20:28 UTC, closed without merging