Customize modes step2
e-mission/e-mission-phone pull request #1120
Opened 2023-12-29 21:37 UTC by jiji14

![Screenshot 2023-12-29 at 1 33 05 PM](https://github.com/e-mission/e-mission-phone/assets/47590587/4931a029-d943-44ed-8f1d-f91d49f409ea)

2024-02-09 20:11 UTC, jiji14 commented
> @jiji14 Can you change target branch to `master`?

Done!

2024-02-10 02:21 UTC, JGreenlee commented
I noticed a few issues while testing this.

I don't know if they were present before; they could be new issues from merging in changes from upstream. I also merged in Step 1 here so we can be sure Step 1 and Step 2 are working together.

Either way, @jiji14 could you take a look?

### Custom Labels from label screen don't appear on profile screen 

Go to the Profile screen > Manage Custom Labels and see the list of current labels (if any). Then go to the Label screen and add a custom label (via "Other..."). Then go back to the Profile screen > Manage Custom Labels, the new label does not appear immediately. After reloading, the new label does appear there

### Custom labels don't appear on label screen until you interact with the "Other" input

On the label screen, I can go to "Other" and add a new custom label. Then if I go to label a new trip, the custom label shows (as expected). But if I kill the app and re-open the app, they appear to have disappeared. When I add a new custom label, I see the old ones again.

2024-02-16 02:08 UTC, jiji14 commented
@JGreenlee 

The error occurred after merging. I fixed the bugs and also took care of the code coverage issue

2024-02-16 17:30 UTC, JGreenlee requested changes
I tested this again and it works really well! The bugs from merging in were probably my mistake (bad merge conflict resolution).

Below are 3 quick suggestions I have, once they are applied I will pass this along!

2024-02-16 17:30 UTC, JGreenlee commented on jest.config.js
> +  coveragePathIgnorePatterns: ['www/js/services/commHelper.ts']
Great, this seems to work!!

Can we add a note here for explanation?

```suggestion
  // several functions in commHelper do not have unit tests; see note in commHelper.test.ts
  coveragePathIgnorePatterns: ['www/js/services/commHelper.ts'],
```

2024-02-16 17:30 UTC, JGreenlee commented on www/js/control/ProfileSettings.tsx
> +        <CustomLabelSettingRow />
This is a good place to put the `<CustomLabelSettingRow>`, but when testing I noticed that `<CustomLabelSettingRow>` shows up in all configurations, even if there are no multilabel choices. Some programs don't have "mode" and "purpose" labels - they just have surveys. If that's the case, custom labels don't apply.

We should show this row conditionally, like below (or a different way if you prefer)
```suggestion
        {appConfig?.survey_info?.['trip-labels'] == 'MULTILABEL' && <CustomLabelSettingRow />}
```

2024-02-16 17:30 UTC, JGreenlee commented on www/js/App.tsx
> +};
```suggestion
```

Duplicated code that can be removed.
I think this was also my mistake from bad merge conflict resolution

2024-02-17 06:09 UTC, jiji14 commented
@JGreenlee 
Thanks for all the suggestions. It looks great so I updated the codes :) 

@shankari 
Please note that server code needs to merge first before this PR.

2024-03-25 19:53 UTC, shankari commented
@jiji14 or @JGreenlee can you resolve the merge conflict? I will likely target another staging release for this week so we can be testing next week.

2024-03-25 19:57 UTC, JGreenlee commented
resolved

2024-07-20 01:00 UTC, shankari approved these changes
I'm going to go ahead and merge this since it is correct, but I think it might need enhancements as part of the CO2 calculations. Right now, when the user adds a new custom mode, we don't store any CO2 information as part of it. It seems like we should, but it is not clear that the end user knows the energy/emissions intensity of the mode that they add.

I can put this up on staging/nrel-commute for now, but we should really decide how we are going to handle this before we move to production in general, since otherwise we have to deal with data migration.

2024-07-20 01:00 UTC, shankari commented on www/js/App.tsx
> +const CUSTOM_LABEL_KEYS_IN_DATABASE = ['mode', 'purpose'];
@JGreenlee don't we need this for replaced mode as well? Or is the expectation that the replaced mode will also share the custom labels from the regular mode?

2024-07-20 01:00 UTC, shankari commented on www/js/survey/multilabel/MultiLabelButtonGroup.tsx
> +                                t('trip-confirm.custom-mode')}
Ah I see that we do in fact use the same values for both `MODE` and `REPLACED_MODE`

2024-07-20 01:00 UTC, merged