Update to "Process start_places and remove copies"
e-mission/e-mission-phone pull request #958
Opened 2023-04-26 17:47 UTC by sebastianbarry

This PR is meant to be a direct upgrade to https://github.com/e-mission/e-mission-phone/pull/951 pointed at the new `may_2023_point_release` branch

I addressed most of your comments from that older PR in this new commit @shankari

2023-04-26 18:01 UTC, sebastianbarry commented
@shankari here is the new e-mission-phone PR for start_confirmed_place changes

2023-04-26 18:31 UTC, shankari requested changes
I think you still need one fix. Happy to merge after that is fixed and you finish re-testing

2023-04-26 18:31 UTC, shankari commented on www/js/diary/infinite_scroll_list.js
> +        tripgj.display_date = moment((tripgj.start_ts || tripgj.enter_ts || tripgj.end_ts || tripgj.exit_ts) * 1000).format('ddd DD MMM YYYY');
don't you need curly braces here for the `if`?

2023-04-27 21:03 UTC, sebastianbarry commented on www/js/diary/infinite_scroll_list.js
> +        tripgj.display_date = moment((tripgj.start_ts || tripgj.enter_ts || tripgj.end_ts || tripgj.exit_ts) * 1000).format('ddd DD MMM YYYY');
```suggestion
        if (tripgj.start_ts || tripgj.enter_ts) {
          tripgj.display_start_time = DiaryHelper.getLocalTimeString(tripgj.start_local_dt || tripgj.enter_local_dt);
        }
        tripgj.display_date = moment((tripgj.start_ts || tripgj.enter_ts || tripgj.end_ts || tripgj.exit_ts) * 1000).format('ddd DD MMM YYYY');
```

2023-04-27 21:53 UTC, sebastianbarry commented
Testing:

| | Screenshot | Explanation |
:---:|:---:|:---:
| Issue | ![Simulator Screen Shot - iPhone 11 - 2023-04-27 at 15 09 47](https://user-images.githubusercontent.com/61334340/234998759-bcaeb936-ca9a-4b0a-8848-b1d15d3752fb.png) ![Simulator Screen Shot - iPhone 11 - 2023-04-27 at 15 09 50](https://user-images.githubusercontent.com/61334340/234998772-65a8ec97-15c5-4888-a3d2-4437b9722fb0.png) ![Simulator Screen Shot - iPhone 11 - 2023-04-27 at 15 10 01](https://user-images.githubusercontent.com/61334340/234998782-2eae9301-2e9d-4864-9d66-73d143bdcfe9.png) | As you can see, when we prefill the survey time for the first place object, the time is incorrect and causes you to not be able to submit without changing the time (it sets the time to whatever the current time is) |
| Solution | ![Simulator Screen Shot - iPhone 11 - 2023-04-27 at 15 51 40](https://user-images.githubusercontent.com/61334340/234998994-8c17b928-2b1d-4af7-9e7f-2b0dac5dc1a1.png)
![Simulator Screen Shot - iPhone 11 - 2023-04-27 at 15 51 45](https://user-images.githubusercontent.com/61334340/234998999-3de7e3b6-3ad6-47f1-861e-666c015391aa.png) | Now, when you click it it prefills correctly and the input matcher works for the first place entry (the issue here was that the begin timestamp did not exist for the first place object, so we have to auto-fill in the begin timestamp as the start of the day for the exit timestamp) |

2023-04-27 22:02 UTC, sebastianbarry commented
Testing with download from server button:

| | | |
:---:|:---:|:---:
| ![Simulator Screen Shot - iPhone 11 - 2023-04-27 at 15 58 40](https://user-images.githubusercontent.com/61334340/235000594-a2ac249d-e4dd-41aa-a98e-a8a4a000b8d0.png) first place object displays properly | ![Simulator Screen Shot - iPhone 11 - 2023-04-27 at 15 58 51](https://user-images.githubusercontent.com/61334340/235000691-52486fd8-598f-41ca-adfc-80875d967444.png) first place object receives input properly | ![Simulator Screen Shot - iPhone 11 - 2023-04-27 at 15 59 25](https://user-images.githubusercontent.com/61334340/235000775-a72c1c5a-07e0-44c7-8ac4-ccea801fe091.png) download from server correctly downloads entries and does not created duplicates |
| ![Simulator Screen Shot - iPhone 11 - 2023-04-27 at 15 59 45](https://user-images.githubusercontent.com/61334340/235000843-8bf13ea0-8cae-4635-9169-33ce6192feb1.png) new first place object is created properly | ![Simulator Screen Shot - iPhone 11 - 2023-04-27 at 15 59 53](https://user-images.githubusercontent.com/61334340/235000881-ee47f443-2a5f-4bf3-b5be-14cee777dd3e.png) new first place object accepts input properly | ![Simulator Screen Shot - iPhone 11 - 2023-04-27 at 16 00 18](https://user-images.githubusercontent.com/61334340/235000910-a38cdefd-444f-4a29-b34c-92587c372c80.png) place additions remain after a refresh on first place objects |

2023-04-27 22:03 UTC, sebastianbarry commented
This change should be good to go @shankari

2023-04-27 22:15 UTC, shankari commented
@sebastianbarry did you test by pushing the entries and re-running the pipeline to make sure that the end-to-end flow works?

2023-04-27 23:14 UTC, sebastianbarry commented
> did you test by pushing the entries and re-running the pipeline to make sure that the end-to-end flow works?

Testing end trip + sync + pipeline run:

| | |
:---:|:---:
| ![Simulator Screen Shot - iPhone 11 - 2023-04-27 at 17 12 49](https://user-images.githubusercontent.com/61334340/235009995-03b632c7-8f25-4b79-95aa-9ab3ab595490.png) | After `end trip + sync` and then running the pipeline again, additions stay within the first place objects and no time-discrepancies are brought about because of the duplicate places/first place object being used |

2023-04-28 00:10 UTC, shankari approved these changes

2023-04-28 00:10 UTC, merged